#!/bin/bash

# --- Revised 3-Clause BSD License ---
# Copyright Semtech Corporation 2022. All rights reserved.
#
# Uplink/Downlink tests
# These tests verify packet transmission and reception, CCA, beacons

. $(dirname $0)/run-tests-common

TESTS="test3b-dnC test3b-dnC_2ant test3b-rx2_2ant test3c-cca test3d-bcns"
CATEGORY="updn"

run_tests "$@"
